JustinTorrance/notez

src/actions/index.js
src/containers/App/App.js
src/reducers/createNoteReducer.js
src/reducers/index.js
src/thunks/fetchNotes.js

- added action creators:
- createNote
- getNotes
- created notesReducer with cases:
- 'CREATE_NOTE'
- 'GET_NOTES'
- updated rootReducer
- created fetchNotes thunk
- dispatch thunk in componentDidMount

Store notes

---

package-lock.json
src/actions/index.js
src/components/Loading/Loading.js
src/containers/App/App.js
src/reducers/index.js
src/reducers/isLoadingReducer.js
src/thunks/fetchNotes.js

- Create isLoading action creator
- Create isLoadingReducer
- Create Loading component
- access "loading" with mapStateToProps for conditional rendering
@JustinTorrance @kimmichurri

Loading error components

---

src/containers/App/App.js
src/containers/CardContainer/CardContainer.js
src/containers/NewNote/NewNote.js
src/index.js

Co-authored-by: Kim Myers <kimberly.achkio@gmail.com>
Co-authored-by: Justin Torrance <justin.torrance91@gmail.com>
- Separated App into NewNote.js and CardContainer.js
- Enabled router

Enable router and create new note component

---

src/actions/index.js
src/reducers/fetchErroredReducer.js
src/reducers/index.js
src/thunks/__tests__/fetchNotes.js
src/thunks/fetchNotes.js

- added fetchErrored action creator 
- added fetchErrored reducer
- updated rootReducer
- updated fetchNotes thunk to dispatch fetchErrored on unsuccessful response
- created test directory in thunk directory
- tested fetchNotes thunk for both happy and sad paths

Test thunk

---

src/components/Card/Card.js
src/containers/CardContainer/CardContainer.js
src/containers/NewNote/NewNote.js

- Add Cards to DOM
- Change note.body to note.listItems
- Display note title
- Display note listItems
@kimmichurri @JustinTorrance

Display notes

---

src/components/Card/Card.js
src/containers/CardContainer/CardContainer.js

- Add id prop to card
- Add delete button for every listItem

Add id prop and delete button to Card

---

src/reducers/__tests__/createNoteReducer.js

- created test directory for reducers
- __ tests __
- tests for createNoteReducer:
- returns default state
- returns state with the added note
- returns state with all of the notes

Test reducers

---

src/actions/index.js
src/components/Card/Card.js
src/reducers/createNoteReducer.js
src/thunks/addNote.js
src/thunks/deleteNote.js

- Create action, reducer, and thunk for DELETE http

Create action for delete

---

src/reducers/__tests__/createNoteReducer.js
src/reducers/__tests__/fetchErroredReducer.js
src/reducers/__tests__/isLoadingReducer.js

- updated createNoteReducer to reflect delete functionality
- wrote complete tests for: 
- fetchErroredReducer
-  isLoadingReducer

More testing

---

src/thunks/__tests__/deleteNote.js

- Create deleteNote.js in __test__
- Test deleteNote thunk
@kimmichurri @JustinTorrance

Test deleteNote.js thunk

---

src/components/Loading/Loading.test.js
src/components/Loading/__snapshots__/Loading.test.js.snap

- wrote snapshot test for Loading.js
- verified snapshot
@jlavar1 @JustinTorrance

Complete snapshot test for Loading.js

---

src/containers/App/App.test.js
src/containers/App/__snapshots__/App.test.js.snap

- wrote snapshot test for App.js for case loading true or false with mock props
- verified snapshot
@jlavar1 @JustinTorrance

Write snapshot tests for both cases of loading

---

src/containers/CardContainer/CardContainer.test.js
src/containers/CardContainer/__snapshots__/CardContainer.test.js.snap

- create mock data
- mocked props function
- wrote snapshot test for CardContainer.js 
- verified snapshot

Write snapshot test with mock data for CardContainer.js

---

src/thunks/updateListItems.js

Co-authored-by: Joshua Lavarine <joshua@lavarine.com>
Co-authored-by: Kim Myers <kimberly.achkio@gmail.com>
- Remove response.json from thunk

Remove excess lines on PUT thunk

---

src/components/Card/Card.js

- List items that are marked completed will have a strike-through

Add conditional inline styling to strike-through completed list items

---

src/thunks/__tests__/addNote.js
src/thunks/__tests__/updateListItems.js

- Test addNote thunk
- Test updateListItems thunk

Test thunks

---

src/actions/index.js
src/components/Card/Card.js
src/reducers/createNoteReducer.js

- Delete list items
- When toggling a list item as complete, it has strike-thru effect and moves to bottom of card

Delete list items

---

package.json
src/containers/App/__snapshots__/App.test.js.snap
src/containers/CardContainer/__snapshots__/CardContainer.test.js.snap

- updated test configuration
- updated and verified snapshots
Co-authored-by: Justin Torrance <justin.torrance91@gmail.com>
Co-authored-by: Joshua Lavarine <joshua@lavarine.com>

Update test configuration

---

src/actions/index.test.js

- createNote
- getNotes
- deleteNoteAction
- isLoading

Test actions

---

src/actions/index.test.js
src/containers/Input/Input.test.js
src/containers/Input/__snapshots__/Input.test.js.snap

Test input

---

src/components/Card/Card.js
src/components/Card/Card.test.js
src/components/Card/__snapshots__/Card.test.js.snap

- add export to Card.js
- import Card.js into Card.test.js
- test snapshot of Card.js

Snapshot and setup Card.test

---

src/containers/NewNote/NewNote.test.js

- completed testing for NewNote.js
- test file: NewNote.test.js

New note test

---

src/actions/index.test.js
src/components/BadPath/__snapshots__/BadPath.test.js.snap
src/containers/App/__snapshots__/App.test.js.snap
src/containers/NewNote/__snapshots__/NewNote.test.js.snap

- updated all snapshots
- completed last two test for actions
- toggleCompleted
- deleteListItem

Test toggleCompleted and deleteListItem

---

src/containers/App/App.js

- Render Card if card.id matches URL patch

Render Card if id matches URL

---

src/containers/App/App.js
src/containers/App/App.test.js
src/containers/App/__snapshots__/App.test.js.snap

Test mdtp in App
